name: Сборка Storybook
on:
  push:
    branches: master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    name: Сборка
    runs-on: ubuntu-latest

    steps:
      - name: Download CSSSR actions
        uses: actions/checkout@v2
        with:
          repository: CSSSR/actions
          token: ${{ secrets.DOWNLOAD_ACTIONS_TOKEN }}
          path: actions

      - uses: actions/checkout@v2
        with:
          path: vega-ui

      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - run: yarn install --frozen-lockfile
        working-directory: ./vega-ui

      - run: yarn build-storybook
        working-directory: ./vega-ui

      - name: Upload static files and deploy storybook
        uses: ./actions/deploy-static-site/v1beta1
        with:
          auth: ${{ secrets.CSSSR_AUTH }}
          project-id: professionals-storybook
          files: professionals/storybook-static
          token: ${{ secrets.GITHUB_TOKEN }}